//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Repository
{
    using System;
    using System.Collections.Generic;
    using Model.Entities;
    
    
    public partial interface IAspNetRoleRepository : Data.Repository.IBaseRepository<AspNetRole>
    {
    }
    
    public partial class AspNetRoleRepository : Data.Repository.BaseRepository<AspNetRole>, IAspNetRoleRepository
    {
    	public AspNetRoleRepository(Entities dbContext) : base(dbContext)
        {
        }
    }
}
