//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Repository
{
    using System;
    using System.Collections.Generic;
    using Model.Entities;
    
    
    public partial interface ITestRepository : Data.Repository.IBaseRepository<Test>
    {
    }
    
    public partial class TestRepository : Data.Repository.BaseRepository<Test>, ITestRepository
    {
    	public TestRepository(Entities dbContext) : base(dbContext)
        {
        }
    }
}
