//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface IAspNetRoleService : Data.Service.IBaseService<AspNetRole>
    {
    }
    
    public partial class AspNetRoleService : Data.Service.BaseService<AspNetRole>, IAspNetRoleService
    {
        public AspNetRoleService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IAspNetRoleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
