//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface IAspNetUserLoginService : Data.Service.IBaseService<AspNetUserLogin>
    {
    }
    
    public partial class AspNetUserLoginService : Data.Service.BaseService<AspNetUserLogin>, IAspNetUserLoginService
    {
        public AspNetUserLoginService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.IAspNetUserLoginRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
