//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Service
{
    using System;
    using System.Collections.Generic;
    using Data.Model.Entities;
    
    
    public partial interface ITestService : Data.Service.IBaseService<Test>
    {
    }
    
    public partial class TestService : Data.Service.BaseService<Test>, ITestService
    {
        public TestService(Data.Infrastructure.IUnitOfWork unitOfWork, Data.Repository.ITestRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
